### PR TITLE
Issue #40 - Update ACF Dependency

### LINKED ISSUE #40: Update the version of ACF
In the `composer.json` update the package definition.

### PR DESCRIPTION
**Pull request by notjb**
Fix #40

### CODE REVIEW

**Review by ptt-homme — APPROVED** [review]
👏 🤘

**Comment by perruche** [comment]
You can remove the ACF option in the rest of the project since it's unused now ?
- `saofile.js`
- `functions.php`

**Comment by ptt-homme** [comment]
> You can remove the ACF option in the rest of the project since it's unused now ?
> 
> * `saofile.js`
> * `functions.php`

@perruche Why would you remove the ACF option? ACF is still present even if we change the way to get it? Am I missing something?

**Comment by perruche** [comment]
> > You can remove the ACF option in the rest of the project since it's unused now ?
> > 
> > * `saofile.js`
> > * `functions.php`
> 
> @perruche Why would you remove the ACF option? ACF is still present even if we change the way to get it? Am I missing something?

no nothing, i missread

**Pull request merged**
