### PR TITLE
Add WPML to the list of plugins

### PR DESCRIPTION
**Pull request by titouanmathis**
This PR adds WPML and its plugins as Composer depencies.

### CODE REVIEW

**Comment by titouanmathis** [comment]
Ping @studiometa/wordpress, this PR is ready for review 😉

**Comment by perruche** [comment]
Are we sure we want to use wpml for multilingual sites ? 
Should we do a benchmark of the existing solutions ?

**Comment by ptt-homme** [comment]
+1 with Ludo. Right now, we do not have, excluding ACF, plugins that are used on all our WordPress sites. This is also true for Wordfence... Why installed plugins that won't be used... Let's have an brainstorming on this?!

**Comment by titouanmathis** [comment]
Closing this as we encountered some bugs when installing WPML with Composer.

**Pull request closed without merging**
